name: 'Slack Notification'
description: 'Send notification to Slack channel'

inputs:
  channel-id:
    description: 'Slack channel ID'
    required: true
  message:
    description: 'Message to send'
    required: true
  bot-token:
    description: 'Slack bot token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Send Slack notification
      uses: slackapi/slack-github-action@v1.25.0
      with:
        method: chat.postMessage
        token: ${{ inputs.bot-token }}
        payload: |
          {
            "channel": "${{ inputs.channel-id }}",
            "text": "${{ inputs.message }}"
          }