platform :ios do
  before_all do
    UI.message("Installing dependencies")
    sh("npm", "ci", "--legacy-peer-deps") # Install npm dependencies
    cocoapods # Install CocoaPods dependencies
  end

  desc "Builds DeveloperApp for Debug and generates an .ipa file"
  lane :debug_internal do
    UI.message("Building DeveloperApp for Debug and generating .ipa")
    gym(
      scheme: "DeveloperApp", # Replace with your app's scheme name
      configuration: "Debug", # Use Debug configuration
      output_directory: "./build", # Directory where the .ipa will be saved
      output_name: "DeveloperApp-Debug.ipa", # Name of the .ipa file
      export_method: "development", # Use development export method for debug builds
      include_bitcode: false, # Optional: Exclude bitcode for faster builds
      include_symbols: true, # Include debug symbols for debugging
    )
  end
end