name: 'Build Android App'
description: 'Builds the Android app using Fastlane'

inputs:
  google_services_json:
    description: 'Base64-encoded google-services.json file'
    required: true
  firebaseAPIKey:
    description: 'Firebase API key'
    required: true
  keystoreBase64: 
    description: 'Base64-encoded Android keystore file'
    required: true
  keystoreAlias:
    description: 'Alias for the Android keystore'
    required: true
  keystorePassword:
    description: 'Password for the Android keystore'
    required: true
  keystoreKeyPassword:
    description: 'Key password for the Android keystore'
    required: true
  playStoreCredentialsBase64:
    description: 'Base64-encoded Play Store credentials JSON file'
    required: true

runs:
  using: composite

  steps:
    - name: "Setup Java 21"
      id: setup-java
      uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 #v4
      with:
        distribution: "temurin"
        java-version: "21"

    - name: Set up Ruby
      uses: ruby/setup-ruby@1a615958ad9d422dd932dc1d5823942ee002799f #v1
      with:
        ruby-version: '3.2'

    - name: Install Fastlane
      run: gem install fastlane
      shell: bash

    - name: Setup Node
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e #v4
      with:
        node-version-file: .nvmrc

    - name: Decode google-services.json
      env:
        GOOGLE_SERVICES_JSON: ${{ inputs.google_services_json }}
      run: |
        echo $GOOGLE_SERVICES_JSON | base64 --decode > android/app/google-services.json
      shell: bash

    - name: Decode upload.keystore
      env:
        KEYSTORE_BASE64: ${{ inputs.keystoreBase64 }}
      run: |
        mkdir -p android/keystores
        echo $KEYSTORE_BASE64 | base64 --decode > android/keystores/upload.keystore
      shell: bash
    
    - name: Decode Play Store credentials
      env:
        PLAY_STORE_CREDENTIALS_BASE64: ${{ inputs.playStoreCredentialsBase64 }}
      run: |
        mkdir -p android/fastlane
        echo $PLAY_STORE_CREDENTIALS_BASE64 | base64 --decode > android/fastlane/play-store-credentials.json
      shell: bash
    # - name: Verify Keystore File
    #   run: |
    #     keytool -list -v -keystore ./android/keystores/upload.keystore -storepass ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
    # shell: bash 
    - name: Build Android Library with Fastlane
      run: |
        cd android
        fastlane android internal submit:false
      shell: bash
      env:
        FIREBASE_API_KEY: ${{ inputs.firebaseAPIKey }}
        ANDROID_KEYSTORE_PATH: ${{ github.workspace }}/android/keystores/upload.keystore
        ANDROID_KEYSTORE_PASSWORD: ${{ inputs.keystorePassword }}
        ANDROID_KEYSTORE_ALIAS: ${{ inputs.keystoreAlias }}
        ANDROID_KEYSTORE_KEY_PASSWORD: ${{ inputs.keystoreKeyPassword }}
        PLAY_STORE_CREDENTIALS_PATH: ${{ github.workspace }}/android/fastlane/play-store-credentials.json

    - name: Copy Android APK to Shared Directory
      run: |
        mkdir -p ${{ github.workspace }}/artifacts/android-app
        if [ -f ./android/app/build/outputs/apk/production/debug/app-production-debug.apk ]; then
          cp ./android/app/build/outputs/apk/production/debug/app-production-debug.apk ${{ github.workspace }}/artifacts/android-app/app-production-debug.apk
        else
          echo "APK not found at the expected path."
          exit 1
        fi
      shell: bash

    - name: Upload apk to artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-app
        path: ${{ github.workspace }}/artifacts/android-app/