name: 'Build iOS App'
description: 'Builds the iOS app using Fastlane'

runs:
  using: 'composite'
  
  steps:
    - name: Hello Function
      run: echo "Hello!"
      shell: bash
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install Fastlane
      run: gem install fastlane
      shell: bash