name: 'Build iOS App'
description: 'Builds the iOS app using Fastlane'

runs:
  using: 'composite'
  
  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install Fastlane
      run: gem install fastlane
      shell: bash

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc