# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

default_platform(:android)

platform :android do
  before_all do
    Dir.chdir("../..") do
      sh("npm", "ci", "--legacy-peer-deps")
      # Special hack to work-around alpine linux problem - File.getCanonicalPath is failing without a reason:
      sh("find node_modules -name '*.gradle' -type f -exec sed -i.bak '/canonicalPath/d' {} +")
    end
  end

  desc "Build development APK"
  lane :debug_internal do
    gradleOptions = {
      "android.injected.version.code" => 1, # Static version code
      "android.injected.version.name" => "1.0.0.dev", # Static version name
    }

    gradle(
      task: "assemble",
      build_type: "Debug",
      flavor: "Production",
      flags: "--stacktrace",
      properties: gradleOptions
    )
  end
end