name: "Build Android"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Retrieve the secrets and decode it to a file
        env:
          UPLOAD_KEYSTORE_BASE64: ${{ secrets.UPLOAD_KEYSTORE_BASE64 }}
          PLAY_STORE_CREDENTIALS_BASE64: ${{ secrets.PLAY_STORE_CREDENTIALS_BASE64 }}
        run: |
          echo $UPLOAD_KEYSTORE_BASE64 | base64 --decode > ./android/keystores/upload.keystore
          echo $PLAY_STORE_CREDENTIALS_BASE64 | base64 --decode > ./android/fastlane/play-store-credentials.json
        shell: bash

      - name: Build Android apk
        uses: ./.github/actions/build_android
        with:
          firebaseAPIKey: ${{ secrets.FIREBASE_API_KEY }}
          keystorePath: ${{ env.ANDROID_KEYSTORE_PATH }}
          keystoreAlias: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          keystorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keystoreKeyPassword: ${{ secrets.ANDROID_KEYSTORE_KEY_PASSWORD }}
