name: Release Make It Native

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g. 1.2.3)"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PAT: ${{ secrets.PAT }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 #v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Run release script
        env:
          MIN_VERSION: ${{ github.event.inputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PAT: ${{ secrets.PAT }}
        run: node scripts/release-make-it-native.mjs

      - name: Send success message
        if: success()
        uses: ./.github/actions/slack-notification
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          message: |
            ✅ *Make It Native automation succeeded!*
            PRs created in:
            • *make-it-native*
            • *mendix/docs*
            Please review and merge. 🙌
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Send failure message
        if: failure()
        uses: ./.github/actions/slack-notification
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          message: |
            ❌ *Make It Native automation failed!*
            Please check the workflow logs for more details. 🛠
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
